### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by godshades** [Melelery/c-binance-future-quant#6]
hi, thanks for sharing, i want ask some question
1. does this avaiable for just simple running bot
2. does this support other vps than alibaba cloud
3. if 1, 2 is ok, can you give tutorial how to config and run

**Comment by Melelery** [comment]
sorry, it's more of an architecture than an implementation

of course it can be built on other cloud servers, or other exchanges

but I don't have enough financial interest so I don't specialize in programming
